//! Batch subscriber definitions: handlers that consume a whole decoded batch per invocation.
//!
//! Generated by `#[subscriber(batch(..))]` and mounted with
//! [`BrokerScope::include`](super::BrokerScope::include); the mount site requires the
//! source's subscriber to implement [`BatchSubscriber`](crate::BatchSubscriber) (natively, or via
//! the [`Buffered`](crate::Buffered) adapter). Mirrors the single-message pipeline:
//! [`BatchDef`] is the [`SubscriberDef`](super::SubscriberDef) counterpart, [`SliceHandler`] the
//! [`Handler`](super::Handler) counterpart, and [`TypedBatch`] the [`Typed`](super::Typed) decode
//! adapter.

#[cfg(feature = "otel")]
use std::sync::LazyLock;
use std::{fmt, future::Future, marker::PhantomData};

#[cfg(feature = "otel")]
use opentelemetry::metrics::Histogram;
#[cfg(feature = "otel")]
use opentelemetry::{KeyValue, global};
use serde::de::DeserializeOwned;
use tokio_util::task::TaskTracker;
use tracing::{error, warn};

use crate::IncomingMessage;

use super::context::Context;
use super::dispatch::Workers;
use super::failure::{FailurePolicies, FailurePolicy};
use super::handler::{HandlerOutcome, HandlerResult};
use super::input::{DecodeWith, InputKind};
use super::metadata::HandlerMetadata;

/// The settlement of one dispatched batch.
///
/// Returned by batch handlers (usually through [`IntoBatchResult`]) and applied by the
/// dispatcher to each message's own `ack` / `nack`.
///
/// Per-element [`HandlerOutcome`]s carry an optional `and_after` continuation each; the uniform
/// form carries at most one, which runs once after the whole batch is settled.
#[derive(Debug)]
#[non_exhaustive]
pub enum BatchResult {
    /// One outcome settles every message of the batch; its continuation (if any) runs once,
    /// after the last message is settled.
    Uniform(HandlerOutcome),
    /// Settlement `i` settles slice element `i`, each with its own optional post-settle
    /// continuation. A length mismatch with the dispatched batch is a bug in the handler: the
    /// unmatched remainder is retried (an extra redelivery beats a silently lost message) and the
    /// mismatch is logged.
    PerElement(Vec<HandlerOutcome>),
}

/// Conversion into a [`BatchResult`], so `#[subscriber(batch(..))]` handlers can return a plain
/// value.
///
/// Implemented for [`BatchResult`] (identity), [`HandlerOutcome`] / `()` / `Result<(), E>` /
/// `Result<HandlerOutcome, E>` (one outcome for the whole batch), and a per-element
/// `Vec<HandlerOutcome>` where element `i` settles slice element `i`.
pub trait IntoBatchResult {
    /// Converts `self` into the settlement the dispatcher applies.
    fn into_batch_result(self) -> BatchResult;
}

impl IntoBatchResult for BatchResult {
    fn into_batch_result(self) -> BatchResult {
        self
    }
}

impl IntoBatchResult for HandlerOutcome {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(self)
    }
}

impl IntoBatchResult for () {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(HandlerOutcome::ack())
    }
}

impl<E> IntoBatchResult for Result<(), E> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(match self {
            Ok(()) => HandlerOutcome::ack(),
            Err(_) => HandlerOutcome::drop(),
        })
    }
}

impl<E> IntoBatchResult for Result<HandlerOutcome, E> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(self.unwrap_or_else(|_| HandlerOutcome::drop()))
    }
}

impl IntoBatchResult for Vec<HandlerOutcome> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::PerElement(self)
    }
}

/// A handler invoked with one whole decoded batch.
///
/// The batch parameter is a slice: per-message broker handles stay with the dispatcher, which
/// settles every message of the batch according to the returned [`BatchResult`] - one uniform
/// outcome, or one outcome per element.
///
/// # Examples
///
/// Closures returning any [`IntoBatchResult`] implement `SliceHandler` automatically:
///
/// ```
/// use ruststream::runtime::{Context, HandlerOutcome, SliceHandler};
///
/// fn assert_slice_handler<T, H: SliceHandler<T>>(_: H) {}
///
/// fn use_closures() {
///     // One outcome for the whole batch.
///     assert_slice_handler::<u32, _>(|batch: &[u32], _ctx: &mut Context| {
///         let _ = batch.len();
///         async { HandlerOutcome::ack() }
///     });
///     // One outcome per element: entries that are not ready yet retry individually.
///     assert_slice_handler::<u32, _>(|batch: &[u32], _ctx: &mut Context| {
///         let outcomes: Vec<HandlerOutcome> = batch
///             .iter()
///             .map(|n| {
///                 if *n == 0 {
///                     HandlerOutcome::retry()
///                 } else {
///                     HandlerOutcome::ack()
///                 }
///             })
///             .collect();
///         async move { outcomes }
///     });
/// }
/// ```
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a batch handler over `{T}`",
    note = "a batch handler declaring Headers<Vec<_>> implements SliceHandlerWithHeaders \
            instead: mount it with include(..), which picks that form from the definition"
)]
pub trait SliceHandler<T, S = ()>: Send + Sync {
    /// Handles one decoded batch, with the per-batch [`Context`] carrying the typed app state `S`.
    fn handle_slice(
        &self,
        batch: &[T],
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = BatchResult> + Send;
}

/// A handler invoked with one whole decoded batch and the typed headers of its elements.
///
/// The counterpart of [`SliceHandler`] for a batch handler that declares
/// `Headers(meta): Headers<Vec<H>>`. Headers are per-delivery, so the batch gets one
/// contract per element: `headers[i]` belongs to `batch[i]`. The two slices are aligned by
/// construction, because an element whose payload or headers fail to materialize is settled by
/// the decode policy and never reaches the handler.
pub trait SliceHandlerWithHeaders<T, H, S = ()>: Send + Sync {
    /// Handles one decoded batch alongside its per-element header contracts. The contracts move
    /// into the handler as the `Vec` the parameter declares; the payload stays a borrowed slice,
    /// as on the plain batch path.
    fn handle_slice(
        &self,
        batch: &[T],
        headers: Vec<H>,
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = BatchResult> + Send;
}

impl<T, F, Fut, S> SliceHandler<T, S> for F
where
    F: Fn(&[T], &mut Context<'_, (), S>) -> Fut + Send + Sync,
    Fut: Future + Send,
    Fut::Output: IntoBatchResult,
{
    fn handle_slice(
        &self,
        batch: &[T],
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = BatchResult> + Send {
        // Build the inner future before the async block so the returned future does not hold
        // `&[T]` (which would demand `T: Sync` for it to be `Send`).
        let fut = (self)(batch, ctx);
        async move { fut.await.into_batch_result() }
    }
}

/// A handler invoked with one whole batch of undecoded payloads.
///
/// The byte-level counterpart of [`SliceHandler`], selected by a `&[&[u8]]` message parameter:
/// a raw batch is the typed batch without the decode step, so the handler sees the payloads as
/// a slice of byte slices borrowed from the batch's own messages, which the dispatcher holds for
/// the duration of the call. Nothing is copied, and the settlement rules are the batch path's.
pub trait RawSliceHandler<S = ()>: Send + Sync {
    /// Handles one batch of payloads, with the per-batch [`Context`] carrying the typed app
    /// state `S`.
    fn handle_slice(
        &self,
        batch: &[&[u8]],
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = BatchResult> + Send;
}

/// A batch handler definition produced by `#[subscriber(batch(..))]`.
///
/// The batch counterpart of [`SubscriberDef`](super::SubscriberDef): same metadata surface, but
/// the handler consumes `&[Input]` and the mount site drives
/// [`BatchSubscriber::batches`](crate::BatchSubscriber::batches) instead of
/// [`Subscriber::stream`](crate::Subscriber::stream).
pub trait BatchDef: Sized {
    /// The input kind of one batch element ([`Decoded<T>`](super::Decoded); the byte kind does
    /// not batch - a borrowed multi-payload view has no owned form to lend it from). The handler
    /// consumes a slice of the kind's owned decode product, `&[T]`.
    type Input: InputKind;

    /// The concrete handler type over batches of the element type.
    ///
    /// As for [`SubscriberDef::Handler`](super::SubscriberDef::Handler), the state-typed bound is
    /// enforced where the def is mounted, not on the trait: a batch handler that reads typed state
    /// is [`SliceHandler<T, St>`](SliceHandler) only for its declared `St`, while one that
    /// ignores state is generic over it.
    type Handler;

    /// The subscription source this handler binds to (see
    /// [`SubscriberDef::Source`](super::SubscriberDef::Source)).
    type Source;

    /// Builds the subscription source (fresh each call).
    fn source(&self) -> Self::Source;

    /// The concurrency policy for this subscriber's dispatch loop (how many batches are in
    /// flight at once). The macro fills this in from the `workers(..)` argument; the default is
    /// sequential dispatch.
    fn workers(&self) -> Workers {
        Workers::sequential()
    }

    /// The failure policy for a batch-handler panic and a per-element decode failure. The macro
    /// fills this in from the `on_failure(panic = .., decode = ..)` argument; the default fails
    /// fast on a panic and drops on a decode failure.
    fn failure_policies(&self) -> FailurePolicies {
        FailurePolicies::default()
    }

    /// An optional human description (from the handler's doc comment), for `AsyncAPI`.
    fn description(&self) -> Option<&str> {
        None
    }

    /// The element type's serialized JSON Schema, when it implements [`schemars::JsonSchema`] and
    /// the `asyncapi` feature is on. The macro fills this in; the default omits it.
    fn input_schema(&self) -> Option<String> {
        None
    }

    /// The serialized JSON Schema of the element type's header contract, when one is declared
    /// and the `asyncapi` feature is on. The default omits it.
    fn headers_schema(&self) -> Option<String> {
        None
    }

    /// The element type's [`Message`](crate::MessageInfo) name, when it implements that trait. The
    /// macro fills this in; the default omits it.
    fn message_name(&self) -> Option<&'static str> {
        None
    }

    /// The element type's [`Message`](crate::MessageInfo) description, when it implements that trait.
    /// The macro fills this in; the default omits it.
    fn message_description(&self) -> Option<&'static str> {
        None
    }

    /// Consumes the definition, returning the handler.
    fn into_handler(self) -> Self::Handler;
}

/// A batch definition whose handler also reads a typed header contract per element.
///
/// Adds the contract type to [`BatchDef`]; everything else (source, workers, failure policies,
/// schemas) is inherited. Implemented by `#[subscriber(batch(..))]` for a handler that declares
/// `Headers(meta): Headers<Vec<H>>`.
pub trait BatchWithHeadersDef: BatchDef {
    /// The header contract parsed from each element's headers.
    type Headers: DeserializeOwned + Send + Sync + 'static;
}

/// Builds the registration metadata for a batch definition mounted under `name`.
pub(crate) fn batch_metadata<D: BatchDef>(name: String, def: &D) -> HandlerMetadata {
    let mut meta = HandlerMetadata::raw(name).with_def_details(
        def.description(),
        def.input_schema(),
        def.headers_schema(),
        def.message_name(),
        def.message_description(),
    );
    meta.input_type = <D::Input as InputKind>::input_label();
    meta
}

/// The dispatch-side consumer of one raw batch: decode, run the handler, settle every delivery.
/// The batch counterpart of [`Handler`](super::Handler) at the raw-message level.
pub(crate) trait BatchHandler<M, S = ()>: Send + Sync {
    /// Consumes one batch of raw deliveries, acknowledging each of them.
    fn handle_batch(
        &self,
        batch: Vec<M>,
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = ()> + Send;
}

/// Build a [`TypedBatch`] that decodes each element with `codec` into `T` and forwards the batch
/// as `&[T]` to `inner`. The adapter tests' constructor; the mounts name the input kind
/// explicitly instead.
#[cfg(test)]
pub(crate) fn typed_batch<M, T, C, H>(
    codec: C,
    inner: H,
) -> TypedBatch<M, super::input::Decoded<T>, C, H>
where
    M: IncomingMessage,
    T: DeserializeOwned + Send + Sync + 'static,
    C: crate::codec::Codec,
{
    TypedBatch {
        codec,
        inner,
        decode: FailurePolicy::Drop,
        _phantom: PhantomData,
    }
}

/// The decode adapter for batches, the [`Typed`](super::Typed) counterpart, generic over the
/// element's input kind.
///
/// Each element decodes independently: failures are settled individually per the `decode`
/// [`FailurePolicy`] and never reach the handler; the rest are passed on as one slice. The
/// [`BatchResult`] the handler returns settles the deliveries behind that slice - uniformly, or
/// element by element.
pub struct TypedBatch<M, Input, DecodeCodec, Inner> {
    codec: DecodeCodec,
    inner: Inner,
    decode: FailurePolicy,
    _phantom: PhantomData<fn(M, Input)>,
}

impl<M, Input, DecodeCodec, Inner> TypedBatch<M, Input, DecodeCodec, Inner> {
    /// Builds the adapter for any element input kind, like [`Typed::over`](super::Typed::over).
    #[must_use]
    pub(crate) fn over(codec: DecodeCodec, inner: Inner) -> Self
    where
        Input: DecodeWith<DecodeCodec>,
    {
        Self {
            codec,
            inner,
            decode: FailurePolicy::Drop,
            _phantom: PhantomData,
        }
    }

    /// Sets the policy applied when the codec fails to decode an element.
    #[must_use]
    pub(crate) fn with_decode(mut self, decode: FailurePolicy) -> Self {
        self.decode = decode;
        self
    }
}

impl<M, Input, DecodeCodec, Inner> fmt::Debug for TypedBatch<M, Input, DecodeCodec, Inner> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TypedBatch")
            .field("decode", &self.decode)
            .finish_non_exhaustive()
    }
}

impl<M, Input, DecodeCodec, Inner, S> BatchHandler<M, S>
    for TypedBatch<M, Input, DecodeCodec, Inner>
where
    M: IncomingMessage,
    Input: DecodeWith<DecodeCodec>,
    DecodeCodec: Send + Sync,
    Inner: SliceHandler<Input::Owned, S>,
    S: Send + Sync,
{
    async fn handle_batch(&self, batch: Vec<M>, ctx: &mut Context<'_, (), S>) {
        let subscription = ctx.name().to_owned();
        let (values, accepted) =
            decode_batch::<M, Input, DecodeCodec, S>(batch, &self.codec, self.decode, ctx).await;
        if accepted.is_empty() {
            return;
        }
        let tasks = ctx.tasks().clone();
        let result = self.inner.handle_slice(&values, ctx).await;
        settle_batch(accepted, result, &subscription, &tasks).await;
    }
}

/// The decode adapter for batch handlers that also read a typed header contract per element.
///
/// The [`TypedBatch`] counterpart for the `Headers(meta): Headers<Vec<H>>` form: each
/// element must both decode and satisfy the header contract to reach the handler, so the payload
/// slice and the header slice stay index-aligned.
pub struct TypedBatchWithHeaders<M, Input, DecodeCodec, HeaderContract, Inner> {
    codec: DecodeCodec,
    inner: Inner,
    decode: FailurePolicy,
    _phantom: PhantomData<fn(M, Input, HeaderContract)>,
}

impl<M, Input, DecodeCodec, HeaderContract, Inner>
    TypedBatchWithHeaders<M, Input, DecodeCodec, HeaderContract, Inner>
{
    /// Builds the adapter, like [`TypedBatch::over`].
    #[must_use]
    pub(crate) fn over(codec: DecodeCodec, inner: Inner) -> Self
    where
        Input: DecodeWith<DecodeCodec>,
    {
        Self {
            codec,
            inner,
            decode: FailurePolicy::Drop,
            _phantom: PhantomData,
        }
    }

    /// Sets the policy applied when an element fails to decode or to satisfy the contract.
    #[must_use]
    pub(crate) fn with_decode(mut self, decode: FailurePolicy) -> Self {
        self.decode = decode;
        self
    }
}

impl<M, Input, DecodeCodec, HeaderContract, Inner> fmt::Debug
    for TypedBatchWithHeaders<M, Input, DecodeCodec, HeaderContract, Inner>
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TypedBatchWithHeaders")
            .field("decode", &self.decode)
            .finish_non_exhaustive()
    }
}

impl<M, Input, DecodeCodec, HeaderContract, Inner, S> BatchHandler<M, S>
    for TypedBatchWithHeaders<M, Input, DecodeCodec, HeaderContract, Inner>
where
    M: IncomingMessage,
    Input: DecodeWith<DecodeCodec>,
    DecodeCodec: Send + Sync,
    HeaderContract: DeserializeOwned + Send + Sync,
    Inner: SliceHandlerWithHeaders<Input::Owned, HeaderContract, S>,
    S: Send + Sync,
{
    async fn handle_batch(&self, batch: Vec<M>, ctx: &mut Context<'_, (), S>) {
        let subscription = ctx.name().to_owned();
        let (values, contracts, accepted) = decode_batch_with_headers::<
            M,
            Input,
            DecodeCodec,
            HeaderContract,
            S,
        >(batch, &self.codec, self.decode, ctx)
        .await;
        if accepted.is_empty() {
            return;
        }
        let tasks = ctx.tasks().clone();
        let result = self.inner.handle_slice(&values, contracts, ctx).await;
        settle_batch(accepted, result, &subscription, &tasks).await;
    }
}

/// The batch adapter of the byte input kind: no codec, no decode, no rejections.
///
/// Every delivery reaches the handler, as a borrowed payload view; the [`BatchResult`] settles
/// the deliveries behind those views exactly as on the typed path.
pub struct RawBatch<M, Inner> {
    inner: Inner,
    _phantom: PhantomData<fn(M)>,
}

impl<M, Inner> RawBatch<M, Inner> {
    /// Builds the adapter over the batch handler, like [`TypedBatch::over`].
    #[must_use]
    pub(crate) fn over(inner: Inner) -> Self {
        Self {
            inner,
            _phantom: PhantomData,
        }
    }
}

impl<M, Inner> fmt::Debug for RawBatch<M, Inner> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RawBatch").finish_non_exhaustive()
    }
}

impl<M, Inner, S> BatchHandler<M, S> for RawBatch<M, Inner>
where
    M: IncomingMessage,
    Inner: RawSliceHandler<S>,
    S: Send + Sync,
{
    async fn handle_batch(&self, batch: Vec<M>, ctx: &mut Context<'_, (), S>) {
        let subscription = ctx.name().to_owned();
        if batch.is_empty() {
            return;
        }
        #[cfg(feature = "otel")]
        record_batch_size(&subscription, batch.len());
        let tasks = ctx.tasks().clone();
        // The views borrow the deliveries, so they are gone before the batch is settled.
        let result = {
            let payloads: Vec<&[u8]> = batch.iter().map(IncomingMessage::payload).collect();
            self.inner.handle_slice(&payloads, ctx).await
        };
        settle_batch(batch, result, &subscription, &tasks).await;
    }
}

/// Applies one [`BatchResult`] to the accepted deliveries behind it - uniformly, or element by
/// element, spawning each per-element continuation on the tracked set after its settle.
pub(crate) async fn settle_batch<M: IncomingMessage>(
    accepted: Vec<M>,
    result: BatchResult,
    subscription: &str,
    tasks: &TaskTracker,
) {
    match result {
        BatchResult::Uniform(mut outcome) => {
            let after = outcome.take_after();
            let status = outcome.outcome();
            for msg in accepted {
                settle(msg, status, subscription).await;
            }
            // The one uniform continuation runs after the whole batch is settled, on the
            // tracked set so a graceful shutdown drains it (at-most-once, like the
            // per-element ones below).
            if let Some(after) = after {
                tasks.spawn(after);
            }
        }
        BatchResult::PerElement(results) => {
            if results.len() != accepted.len() {
                error!(
                    target: "ruststream::dispatch",
                    subscription = %subscription,
                    expected = accepted.len(),
                    returned = results.len(),
                    "per-element outcome count does not match the batch; \
                     retrying the unmatched remainder",
                );
            }
            let mut results = results.into_iter();
            for msg in accepted {
                // An unmatched message gets retried: an extra redelivery beats losing it.
                let mut result = results.next().unwrap_or_else(HandlerOutcome::retry);
                let after = result.take_after();
                settle(msg, result.outcome(), subscription).await;
                // The continuation runs after this element is settled, on the tracked set so a
                // graceful shutdown drains it. At-most-once: a lost or panicking continuation
                // never redelivers the already-settled message.
                if let Some(after) = after {
                    tasks.spawn(after);
                }
            }
        }
    }
}

/// The `ruststream.batch.size` histogram: decoded batch sizes, per destination. Batch handlers
/// bypass the per-message otel layer (the documented middleware exception), so the metric is
/// recorded at the batch decode choke point every batch form passes through instead.
///
/// Built off the process-global meter, not an `Otel` handle. Until
/// `Otel::builder().init()` installs the SDK's global provider the global meter is
/// a no-op, so an app without the exporters records nothing; the instrument binds to whatever
/// provider is global at the first dispatched batch, and the documented wiring runs `init()`
/// before `app.start()`.
#[cfg(feature = "otel")]
static BATCH_SIZE: LazyLock<Histogram<u64>> = LazyLock::new(|| {
    global::meter("ruststream")
        .u64_histogram("ruststream.batch.size")
        .with_unit("{message}")
        .with_description("Decoded batch sizes handed to batch handlers.")
        .build()
});

/// Records one decoded batch's size under its destination.
#[cfg(feature = "otel")]
fn record_batch_size(destination: &str, len: usize) {
    // Batches beyond u64 elements do not exist.
    #[allow(clippy::cast_possible_truncation)]
    BATCH_SIZE.record(
        len as u64,
        &[KeyValue::new(
            "messaging.destination.name",
            destination.to_owned(),
        )],
    );
}

/// Decodes each element of one raw batch independently: failures are settled per the `decode`
/// [`FailurePolicy`] and never reach the handler; the rest pass through, each decoded value paired
/// with its delivery (`values[i]` decodes `accepted[i]`). A `fail_fast` decode policy tears the
/// service down via `ctx` and drops the offending element so it is not requeued into the failure.
///
/// Takes `&mut Context` (rather than `&Context`) so the future stays `Send`: `Context` carries
/// post-settle hooks (boxed `Send` futures that are not `Sync`), so holding a shared `&Context`
/// across an `.await` would wrongly require `Context: Sync`.
// The `&mut` is for Send-ness, not mutation (only `&self` methods are called), so the lint fires.
#[allow(clippy::needless_pass_by_ref_mut)]
pub(crate) async fn decode_batch<M, Input, DecodeCodec, S>(
    batch: Vec<M>,
    codec: &DecodeCodec,
    decode: FailurePolicy,
    ctx: &mut Context<'_, (), S>,
) -> (Vec<Input::Owned>, Vec<M>)
where
    M: IncomingMessage,
    Input: DecodeWith<DecodeCodec>,
    DecodeCodec: Sync,
    S: Send + Sync,
{
    let subscription = ctx.name().to_owned();
    let mut values = Vec::with_capacity(batch.len());
    let mut accepted = Vec::with_capacity(batch.len());
    for msg in batch {
        match Input::decode(codec, msg.payload(), msg.headers()) {
            Ok(value) => {
                values.push(value);
                accepted.push(msg);
            }
            Err(err) => {
                warn!(
                    target: "ruststream::dispatch",
                    subscription = %subscription,
                    message_type = Input::input_label(),
                    error = %err,
                    "codec decode failed",
                );
                let outcome = rejection(&err, "batch decode failed", decode, ctx);
                settle(msg, outcome, &subscription).await;
            }
        }
    }
    // Only batches that reach a handler count: a fully-rejected batch is short-circuited by the
    // callers and would skew the size distribution with zeros.
    #[cfg(feature = "otel")]
    if !accepted.is_empty() {
        record_batch_size(&subscription, values.len());
    }
    (values, accepted)
}

/// The settlement of one element the handler will never see, per the subscriber's decode policy.
/// Shared by the payload decode and the header contract, which are the same class of bad external
/// input. Not `async`: the outcome is decided before the delivery is settled, so the borrowed
/// error never crosses an await.
fn rejection<S>(
    err: &impl fmt::Display,
    reason: &str,
    decode: FailurePolicy,
    ctx: &Context<'_, (), S>,
) -> HandlerResult {
    match decode {
        FailurePolicy::FailFast => {
            ctx.fail_fast(&format!("{reason}: {err}"));
            HandlerResult::drop()
        }
        other => other.settlement().unwrap_or_else(HandlerResult::drop),
    }
}

/// Decodes each element and parses its headers into `H`, keeping the two products aligned: an
/// element that fails either step is settled by the decode policy and dropped from both.
// The exclusive borrow is what keeps the returned future `Send`: a shared `&Context` would demand
// `Sync` from the post-settle hooks it carries, which are boxed futures.
#[allow(clippy::needless_pass_by_ref_mut)]
pub(crate) async fn decode_batch_with_headers<M, Input, DecodeCodec, H, S>(
    batch: Vec<M>,
    codec: &DecodeCodec,
    decode: FailurePolicy,
    ctx: &mut Context<'_, (), S>,
) -> (Vec<Input::Owned>, Vec<H>, Vec<M>)
where
    M: IncomingMessage,
    Input: DecodeWith<DecodeCodec>,
    DecodeCodec: Sync,
    H: DeserializeOwned,
    S: Send + Sync,
{
    let subscription = ctx.name().to_owned();
    let mut values = Vec::with_capacity(batch.len());
    let mut contracts = Vec::with_capacity(batch.len());
    let mut accepted = Vec::with_capacity(batch.len());
    for msg in batch {
        let value = match Input::decode(codec, msg.payload(), msg.headers()) {
            Ok(value) => value,
            Err(err) => {
                warn!(
                    target: "ruststream::dispatch",
                    subscription = %subscription,
                    message_type = Input::input_label(),
                    error = %err,
                    "codec decode failed",
                );
                let outcome = rejection(&err, "batch decode failed", decode, ctx);
                settle(msg, outcome, &subscription).await;
                continue;
            }
        };
        match msg.headers().to_typed::<H>() {
            Ok(contract) => {
                values.push(value);
                contracts.push(contract);
                accepted.push(msg);
            }
            Err(err) => {
                warn!(
                    target: "ruststream::dispatch",
                    subscription = %subscription,
                    headers_type = std::any::type_name::<H>(),
                    error = %err,
                    "typed header extraction failed",
                );
                let outcome = rejection(&err, "batch header extraction failed", decode, ctx);
                settle(msg, outcome, &subscription).await;
            }
        }
    }
    #[cfg(feature = "otel")]
    if !accepted.is_empty() {
        record_batch_size(&subscription, values.len());
    }
    (values, contracts, accepted)
}

/// Applies one settlement to one delivery's own `ack` / `nack`.
pub(crate) async fn settle<M: IncomingMessage>(msg: M, result: HandlerResult, subscription: &str) {
    let ack_result = match result {
        HandlerResult::Ack => msg.ack().await,
        HandlerResult::Nack { requeue } => msg.nack(requeue).await,
        HandlerResult::NackAfter { delay } => msg.nack_after(delay).await,
    };
    if let Err(err) = ack_result {
        warn!(
            target: "ruststream::dispatch",
            subscription = %subscription,
            error = %err,
            "ack / nack failed",
        );
    }
}

#[cfg(all(test, feature = "memory", feature = "json"))]
mod tests;
