//! Batch subscriber definitions: handlers that consume a whole decoded batch per invocation.
//!
//! Generated by `#[subscriber(batch(..))]` and mounted with
//! [`BrokerScope::include_batch`](super::BrokerScope::include_batch); the mount site requires the
//! source's subscriber to implement [`BatchSubscriber`](crate::BatchSubscriber) (natively, or via
//! the [`Buffered`](crate::Buffered) adapter). Mirrors the single-message pipeline:
//! [`BatchDef`] is the [`SubscriberDef`](super::SubscriberDef) counterpart, [`SliceHandler`] the
//! [`Handler`](super::Handler) counterpart, and [`TypedBatch`] the [`Typed`](super::Typed) decode
//! adapter.

#[cfg(feature = "otel")]
use std::sync::LazyLock;
use std::{future::Future, marker::PhantomData};

#[cfg(feature = "otel")]
use opentelemetry::metrics::Histogram;
#[cfg(feature = "otel")]
use opentelemetry::{KeyValue, global};
use serde::de::DeserializeOwned;
use tokio_util::task::TaskTracker;
use tracing::{error, warn};

use crate::IncomingMessage;
use crate::codec::Codec;

use super::context::Context;
use super::dispatch::Workers;
use super::failure::{FailurePolicies, FailurePolicy};
use super::handler::{HandlerResult, Settle};
use super::input::{DecodeWith, Decoded, InputKind};
use super::metadata::HandlerMetadata;

/// The settlement of one dispatched batch.
///
/// Returned by batch handlers (usually through [`IntoBatchResult`]) and applied by the
/// dispatcher to each message's own `ack` / `nack`.
///
/// Per-element [`Settle`]s carry an optional `and_after` continuation each; the uniform form is a
/// bare outcome, since one continuation cannot fan out to every message of the batch.
#[derive(Debug)]
#[non_exhaustive]
pub enum BatchResult {
    /// One outcome settles every message of the batch.
    Uniform(HandlerResult),
    /// Settlement `i` settles slice element `i`, each with its own optional post-settle
    /// continuation. A length mismatch with the dispatched batch is a bug in the handler: the
    /// unmatched remainder is retried (an extra redelivery beats a silently lost message) and the
    /// mismatch is logged.
    PerElement(Vec<Settle>),
}

/// Conversion into a [`BatchResult`], so `#[subscriber(batch(..))]` handlers can return a plain
/// value.
///
/// Implemented for [`BatchResult`] (identity), [`HandlerResult`] / `()` / `Result<(), E>` /
/// `Result<HandlerResult, E>` (one outcome for the whole batch), and a per-element vector
/// (`Vec<Settle>`, or `Vec<HandlerResult>`) where element `i` settles slice element `i`.
pub trait IntoBatchResult {
    /// Converts `self` into the settlement the dispatcher applies.
    fn into_batch_result(self) -> BatchResult;
}

impl IntoBatchResult for BatchResult {
    fn into_batch_result(self) -> BatchResult {
        self
    }
}

impl IntoBatchResult for HandlerResult {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(self)
    }
}

impl IntoBatchResult for () {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(HandlerResult::Ack)
    }
}

impl<E> IntoBatchResult for Result<(), E> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(match self {
            Ok(()) => HandlerResult::Ack,
            Err(_) => HandlerResult::drop(),
        })
    }
}

impl<E> IntoBatchResult for Result<HandlerResult, E> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::Uniform(self.unwrap_or_else(|_| HandlerResult::drop()))
    }
}

impl IntoBatchResult for Vec<Settle> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::PerElement(self)
    }
}

impl IntoBatchResult for Vec<HandlerResult> {
    fn into_batch_result(self) -> BatchResult {
        BatchResult::PerElement(self.into_iter().map(Settle::from).collect())
    }
}

/// A handler invoked with one whole decoded batch.
///
/// The batch parameter is a slice: per-message broker handles stay with the dispatcher, which
/// settles every message of the batch according to the returned [`BatchResult`] - one uniform
/// outcome, or one outcome per element.
///
/// # Examples
///
/// Closures returning any [`IntoBatchResult`] implement `SliceHandler` automatically:
///
/// ```
/// use ruststream::runtime::{Context, HandlerResult, SliceHandler};
///
/// fn assert_slice_handler<T, H: SliceHandler<T>>(_: H) {}
///
/// fn use_closures() {
///     // One outcome for the whole batch.
///     assert_slice_handler::<u32, _>(|batch: &[u32], _ctx: &mut Context| {
///         let _ = batch.len();
///         async { HandlerResult::Ack }
///     });
///     // One outcome per element: entries that are not ready yet retry individually.
///     assert_slice_handler::<u32, _>(|batch: &[u32], _ctx: &mut Context| {
///         let outcomes: Vec<HandlerResult> = batch
///             .iter()
///             .map(|n| {
///                 if *n == 0 {
///                     HandlerResult::retry()
///                 } else {
///                     HandlerResult::Ack
///                 }
///             })
///             .collect();
///         async move { outcomes }
///     });
/// }
/// ```
pub trait SliceHandler<T, S = ()>: Send + Sync {
    /// Handles one decoded batch, with the per-batch [`Context`] carrying the typed app state `S`.
    fn handle_slice(
        &self,
        batch: &[T],
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = BatchResult> + Send;
}

impl<T, F, Fut, S> SliceHandler<T, S> for F
where
    F: Fn(&[T], &mut Context<'_, (), S>) -> Fut + Send + Sync,
    Fut: Future + Send,
    Fut::Output: IntoBatchResult,
{
    fn handle_slice(
        &self,
        batch: &[T],
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = BatchResult> + Send {
        // Build the inner future before the async block so the returned future does not hold
        // `&[T]` (which would demand `T: Sync` for it to be `Send`).
        let fut = (self)(batch, ctx);
        async move { fut.await.into_batch_result() }
    }
}

/// A batch handler definition produced by `#[subscriber(batch(..))]`.
///
/// The batch counterpart of [`SubscriberDef`](super::SubscriberDef): same metadata surface, but
/// the handler consumes `&[Input]` and the mount site drives
/// [`BatchSubscriber::batches`](crate::BatchSubscriber::batches) instead of
/// [`Subscriber::stream`](crate::Subscriber::stream).
pub trait BatchDef: Sized {
    /// The input kind of one batch element ([`Decoded<T>`](super::Decoded); the byte kind does
    /// not batch - a borrowed multi-payload view has no owned form to lend it from). The handler
    /// consumes a slice of the kind's owned decode product, `&[T]`.
    type Input: InputKind;

    /// The concrete handler type over batches of the element type.
    ///
    /// As for [`SubscriberDef::Handler`](super::SubscriberDef::Handler), the state-typed bound is
    /// enforced where the def is mounted, not on the trait: a batch handler that reads typed state
    /// is [`SliceHandler<T, St>`](SliceHandler) only for its declared `St`, while one that
    /// ignores state is generic over it.
    type Handler;

    /// The subscription source this handler binds to (see
    /// [`SubscriberDef::Source`](super::SubscriberDef::Source)).
    type Source;

    /// Builds the subscription source (fresh each call).
    fn source(&self) -> Self::Source;

    /// The concurrency policy for this subscriber's dispatch loop (how many batches are in
    /// flight at once). The macro fills this in from the `workers(..)` argument; the default is
    /// sequential dispatch.
    fn workers(&self) -> Workers {
        Workers::sequential()
    }

    /// The failure policy for a batch-handler panic and a per-element decode failure. The macro
    /// fills this in from the `on_failure(panic = .., decode = ..)` argument; the default fails
    /// fast on a panic and drops on a decode failure.
    fn failure_policies(&self) -> FailurePolicies {
        FailurePolicies::default()
    }

    /// An optional human description (from the handler's doc comment), for `AsyncAPI`.
    fn description(&self) -> Option<&str> {
        None
    }

    /// The element type's serialized JSON Schema, when it implements [`schemars::JsonSchema`] and
    /// the `asyncapi` feature is on. The macro fills this in; the default omits it.
    fn input_schema(&self) -> Option<String> {
        None
    }

    /// The serialized JSON Schema of the element type's header contract, when one is declared
    /// and the `asyncapi` feature is on. The default omits it.
    fn headers_schema(&self) -> Option<String> {
        None
    }

    /// The element type's [`Message`](crate::Message) name, when it implements that trait. The
    /// macro fills this in; the default omits it.
    fn message_name(&self) -> Option<&'static str> {
        None
    }

    /// The element type's [`Message`](crate::Message) description, when it implements that trait.
    /// The macro fills this in; the default omits it.
    fn message_description(&self) -> Option<&'static str> {
        None
    }

    /// Consumes the definition, returning the handler.
    fn into_handler(self) -> Self::Handler;
}

/// Builds the registration metadata for a batch definition mounted under `name`.
pub(crate) fn batch_metadata<D: BatchDef>(name: String, def: &D) -> HandlerMetadata {
    let mut meta = HandlerMetadata::raw(name).with_def_details(
        def.description(),
        def.input_schema(),
        def.headers_schema(),
        def.message_name(),
        def.message_description(),
    );
    meta.input_type = <D::Input as InputKind>::input_label();
    meta
}

/// The dispatch-side consumer of one raw batch: decode, run the handler, settle every delivery.
/// The batch counterpart of [`Handler`](super::Handler) at the raw-message level.
pub(crate) trait BatchHandler<M, S = ()>: Send + Sync {
    /// Consumes one batch of raw deliveries, acknowledging each of them.
    fn handle_batch(
        &self,
        batch: Vec<M>,
        ctx: &mut Context<'_, (), S>,
    ) -> impl Future<Output = ()> + Send;
}

/// Build a [`TypedBatch`] that decodes each element with `codec` into `T` and forwards the batch
/// as `&[T]` to `inner`.
pub(crate) fn typed_batch<M, T, C, H>(codec: C, inner: H) -> TypedBatch<M, Decoded<T>, C, H>
where
    M: IncomingMessage,
    T: DeserializeOwned + Send + Sync + 'static,
    C: Codec,
{
    TypedBatch {
        codec,
        inner,
        decode: FailurePolicy::Drop,
        _phantom: PhantomData,
    }
}

/// The decode adapter for batches, the [`Typed`](super::Typed) counterpart, generic over the
/// element's input kind.
///
/// Each element decodes independently: failures are settled individually per the `decode`
/// [`FailurePolicy`] and never reach the handler; the rest are passed on as one slice. The
/// [`BatchResult`] the handler returns settles the deliveries behind that slice - uniformly, or
/// element by element.
pub struct TypedBatch<M, Input, DecodeCodec, Inner> {
    codec: DecodeCodec,
    inner: Inner,
    decode: FailurePolicy,
    _phantom: PhantomData<fn(M, Input)>,
}

impl<M, Input, DecodeCodec, Inner> TypedBatch<M, Input, DecodeCodec, Inner> {
    /// Builds the adapter for any element input kind, like [`Typed::over`](super::Typed::over).
    #[must_use]
    pub(crate) fn over(codec: DecodeCodec, inner: Inner) -> Self
    where
        Input: DecodeWith<DecodeCodec>,
    {
        Self {
            codec,
            inner,
            decode: FailurePolicy::Drop,
            _phantom: PhantomData,
        }
    }

    /// Sets the policy applied when the codec fails to decode an element.
    #[must_use]
    pub(crate) fn with_decode(mut self, decode: FailurePolicy) -> Self {
        self.decode = decode;
        self
    }
}

impl<M, Input, DecodeCodec, Inner> std::fmt::Debug for TypedBatch<M, Input, DecodeCodec, Inner> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TypedBatch")
            .field("decode", &self.decode)
            .finish_non_exhaustive()
    }
}

impl<M, Input, DecodeCodec, Inner, S> BatchHandler<M, S>
    for TypedBatch<M, Input, DecodeCodec, Inner>
where
    M: IncomingMessage,
    Input: DecodeWith<DecodeCodec>,
    DecodeCodec: Send + Sync,
    Inner: SliceHandler<Input::Owned, S>,
    S: Send + Sync,
{
    async fn handle_batch(&self, batch: Vec<M>, ctx: &mut Context<'_, (), S>) {
        let subscription = ctx.name().to_owned();
        let (values, accepted) =
            decode_batch::<M, Input, DecodeCodec, S>(batch, &self.codec, self.decode, ctx).await;
        if accepted.is_empty() {
            return;
        }
        let tasks = ctx.tasks().clone();
        let result = self.inner.handle_slice(&values, ctx).await;
        settle_batch(accepted, result, &subscription, &tasks).await;
    }
}

/// Applies one [`BatchResult`] to the accepted deliveries behind it - uniformly, or element by
/// element, spawning each per-element continuation on the tracked set after its settle.
pub(crate) async fn settle_batch<M: IncomingMessage>(
    accepted: Vec<M>,
    result: BatchResult,
    subscription: &str,
    tasks: &TaskTracker,
) {
    match result {
        BatchResult::Uniform(result) => {
            for msg in accepted {
                settle(msg, result, subscription).await;
            }
        }
        BatchResult::PerElement(results) => {
            if results.len() != accepted.len() {
                error!(
                    target: "ruststream::dispatch",
                    subscription = %subscription,
                    expected = accepted.len(),
                    returned = results.len(),
                    "per-element outcome count does not match the batch; \
                     retrying the unmatched remainder",
                );
            }
            let mut results = results.into_iter();
            for msg in accepted {
                // An unmatched message gets retried: an extra redelivery beats losing it.
                let mut result = results
                    .next()
                    .unwrap_or_else(|| HandlerResult::retry().into());
                let after = result.take_after();
                settle(msg, result.outcome(), subscription).await;
                // The continuation runs after this element is settled, on the tracked set so a
                // graceful shutdown drains it. At-most-once: a lost or panicking continuation
                // never redelivers the already-settled message.
                if let Some(after) = after {
                    tasks.spawn(after);
                }
            }
        }
    }
}

/// The `ruststream.batch.size` histogram: decoded batch sizes, per destination. Batch handlers
/// bypass the per-message otel layer (the documented middleware exception), so the metric is
/// recorded at the batch decode choke point every batch form passes through instead.
///
/// Built off the process-global meter rather than an `Otel` handle: threading instruments into
/// the dispatch would couple the runtime to the otel wiring for a per-batch (not per-message)
/// record. Until `Otel::builder().init()` installs the SDK's global provider the global meter is
/// a no-op, so an app without the exporters records nothing; the instrument binds to whatever
/// provider is global at the first dispatched batch, and the documented wiring runs `init()`
/// before `app.start()`.
#[cfg(feature = "otel")]
static BATCH_SIZE: LazyLock<Histogram<u64>> = LazyLock::new(|| {
    global::meter("ruststream")
        .u64_histogram("ruststream.batch.size")
        .with_unit("{message}")
        .with_description("Decoded batch sizes handed to batch handlers.")
        .build()
});

/// Records one decoded batch's size under its destination.
#[cfg(feature = "otel")]
fn record_batch_size(destination: &str, len: usize) {
    // Batches beyond u64 elements do not exist.
    #[allow(clippy::cast_possible_truncation)]
    BATCH_SIZE.record(
        len as u64,
        &[KeyValue::new(
            "messaging.destination.name",
            destination.to_owned(),
        )],
    );
}

/// Decodes each element of one raw batch independently: failures are settled per the `decode`
/// [`FailurePolicy`] and never reach the handler; the rest pass through, each decoded value paired
/// with its delivery (`values[i]` decodes `accepted[i]`). A `fail_fast` decode policy tears the
/// service down via `ctx` and drops the offending element so it is not requeued into the failure.
///
/// Takes `&mut Context` (rather than `&Context`) so the future stays `Send`: `Context` carries
/// post-settle hooks (boxed `Send` futures that are not `Sync`), so holding a shared `&Context`
/// across an `.await` would wrongly require `Context: Sync`.
// The `&mut` is for Send-ness, not mutation (only `&self` methods are called), so the lint fires.
#[allow(clippy::needless_pass_by_ref_mut)]
pub(crate) async fn decode_batch<M, Input, DecodeCodec, S>(
    batch: Vec<M>,
    codec: &DecodeCodec,
    decode: FailurePolicy,
    ctx: &mut Context<'_, (), S>,
) -> (Vec<Input::Owned>, Vec<M>)
where
    M: IncomingMessage,
    Input: DecodeWith<DecodeCodec>,
    DecodeCodec: Sync,
    S: Send + Sync,
{
    let subscription = ctx.name().to_owned();
    let mut values = Vec::with_capacity(batch.len());
    let mut accepted = Vec::with_capacity(batch.len());
    for msg in batch {
        match Input::decode(codec, msg.payload()) {
            Ok(value) => {
                values.push(value);
                accepted.push(msg);
            }
            Err(err) => {
                warn!(
                    target: "ruststream::dispatch",
                    subscription = %subscription,
                    message_type = Input::input_label(),
                    error = %err,
                    "codec decode failed",
                );
                let outcome = match decode {
                    FailurePolicy::FailFast => {
                        ctx.fail_fast(&format!("batch decode failed: {err}"));
                        HandlerResult::drop()
                    }
                    other => other.settlement().unwrap_or_else(HandlerResult::drop),
                };
                settle(msg, outcome, &subscription).await;
            }
        }
    }
    // Only batches that reach a handler count: a fully-rejected batch is short-circuited by the
    // callers and would skew the size distribution with zeros.
    #[cfg(feature = "otel")]
    if !accepted.is_empty() {
        record_batch_size(&subscription, values.len());
    }
    (values, accepted)
}

/// Applies one settlement to one delivery's own `ack` / `nack`.
pub(crate) async fn settle<M: IncomingMessage>(msg: M, result: HandlerResult, subscription: &str) {
    let ack_result = match result {
        HandlerResult::Ack => msg.ack().await,
        HandlerResult::Nack { requeue } => msg.nack(requeue).await,
        HandlerResult::NackAfter { delay } => msg.nack_after(delay).await,
    };
    if let Err(err) = ack_result {
        warn!(
            target: "ruststream::dispatch",
            subscription = %subscription,
            error = %err,
            "ack / nack failed",
        );
    }
}

#[cfg(all(test, feature = "memory", feature = "json"))]
mod tests {
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::{Arc, Mutex, OnceLock};

    use futures::StreamExt;
    use tokio_util::sync::CancellationToken;

    use super::super::dispatch::Delivery;
    use super::super::failure::ErrorShutdown;
    use super::super::input::Decoded;
    use super::*;
    use crate::codec::JsonCodec;
    use crate::memory::{ConnectedMemoryBroker, MemoryBroker, MemoryMessage, MemorySubscriber};
    use crate::{
        AckError, BatchSubscriber, Headers, Name, OutgoingMessage, Publisher, Subscriber,
        SubscriptionSource,
    };

    async fn publish_numbers(broker: &MemoryBroker, name: &str, numbers: &[u32]) {
        let publisher = broker.publisher();
        for n in numbers {
            publisher
                .publish(OutgoingMessage::new(name, &serde_json::to_vec(n).unwrap()))
                .await
                .unwrap();
        }
    }

    async fn publish_payloads(broker: &MemoryBroker, name: &str, payloads: &[&[u8]]) {
        let publisher = broker.publisher();
        for payload in payloads {
            publisher
                .publish(OutgoingMessage::new(name, payload))
                .await
                .unwrap();
        }
    }

    async fn pull_batch(sub: &mut MemorySubscriber) -> Vec<MemoryMessage> {
        let mut stream = std::pin::pin!(sub.batches());
        stream.next().await.unwrap().unwrap()
    }

    #[tokio::test]
    async fn per_element_outcomes_settle_individually() {
        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("selective");
        publish_numbers(&broker, "selective", &[0, 1, 2]).await;

        // 0 acks, 1 retries, 2 drops: only 1 may come back.
        let handler = typed_batch(JsonCodec, |batch: &[u32], _ctx: &mut Context| {
            let outcomes: Vec<HandlerResult> = batch
                .iter()
                .map(|n| match n {
                    1 => HandlerResult::retry(),
                    2 => HandlerResult::drop(),
                    _ => HandlerResult::Ack,
                })
                .collect();
            async move { outcomes }
        });

        let state = ();
        let delivery = Delivery::empty();
        let headers = Headers::new();
        let mut ctx = Context::new("selective", &headers, &state, (), &delivery);
        let batch = pull_batch(&mut sub).await;
        assert_eq!(batch.len(), 3);
        handler.handle_batch(batch, &mut ctx).await;

        let redelivered = pull_batch(&mut sub).await;
        let payloads: Vec<&[u8]> = redelivered.iter().map(IncomingMessage::payload).collect();
        assert_eq!(payloads, [b"1"]);
        for msg in redelivered {
            msg.ack().await.unwrap();
        }
        let mut stream = std::pin::pin!(sub.stream());
        assert!(futures::poll!(stream.next()).is_pending());
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn per_element_continuations_run_after_settle() {
        use tokio::sync::Notify;

        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("after-batch");
        publish_numbers(&broker, "after-batch", &[0, 1]).await;

        // Element 0 acks with a continuation; element 1 retries with no continuation.
        let ran = Arc::new(Notify::new());
        let signal = Arc::clone(&ran);
        let handler = typed_batch(JsonCodec, move |batch: &[u32], _ctx: &mut Context| {
            let signal = Arc::clone(&signal);
            let outcomes: Vec<Settle> = batch
                .iter()
                .map(|n| {
                    if *n == 0 {
                        let signal = Arc::clone(&signal);
                        HandlerResult::ack().and_after(async move { signal.notify_one() })
                    } else {
                        HandlerResult::retry().into()
                    }
                })
                .collect();
            async move { outcomes }
        });

        let tasks = TaskTracker::new();
        let state = ();
        let delivery = Delivery::with_tasks(tasks.clone());
        let headers = Headers::new();
        let mut ctx = Context::new("after-batch", &headers, &state, (), &delivery);
        let batch = pull_batch(&mut sub).await;
        handler.handle_batch(batch, &mut ctx).await;

        // The continuation for element 0 runs on the tracked set after settling.
        ran.notified().await;
        tasks.close();
        tasks.wait().await;

        // Element 1 (no continuation) retried and comes back; element 0 is gone.
        let redelivered = pull_batch(&mut sub).await;
        let payloads: Vec<&[u8]> = redelivered.iter().map(IncomingMessage::payload).collect();
        assert_eq!(payloads, [b"1"]);
        for msg in redelivered {
            msg.ack().await.unwrap();
        }
    }

    #[tokio::test]
    async fn unmatched_remainder_is_retried() {
        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("short");
        publish_numbers(&broker, "short", &[0, 1, 2]).await;

        // A buggy handler returning one outcome for a batch of three: the unmatched two retry.
        let handler = typed_batch(JsonCodec, |_batch: &[u32], _ctx: &mut Context| async {
            vec![HandlerResult::Ack]
        });

        let state = ();
        let delivery = Delivery::empty();
        let headers = Headers::new();
        let mut ctx = Context::new("short", &headers, &state, (), &delivery);
        let batch = pull_batch(&mut sub).await;
        assert_eq!(batch.len(), 3);
        handler.handle_batch(batch, &mut ctx).await;

        let redelivered = pull_batch(&mut sub).await;
        let payloads: Vec<&[u8]> = redelivered.iter().map(IncomingMessage::payload).collect();
        assert_eq!(payloads, [b"1", b"2"]);
        for msg in redelivered {
            msg.ack().await.unwrap();
        }
    }

    // Paused time (current-thread runtime): the per-element delay auto-advances.
    #[tokio::test(start_paused = true)]
    async fn per_element_outcomes_carry_delays() {
        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("delayed");
        publish_numbers(&broker, "delayed", &[0, 1]).await;

        // 0 acks; 1 retries no sooner than five seconds from now.
        let handler = typed_batch(JsonCodec, |batch: &[u32], _ctx: &mut Context| {
            let outcomes: Vec<HandlerResult> = batch
                .iter()
                .map(|n| match n {
                    1 => HandlerResult::retry_after(std::time::Duration::from_secs(5)),
                    _ => HandlerResult::Ack,
                })
                .collect();
            async move { outcomes }
        });

        let state = ();
        let delivery = Delivery::empty();
        let headers = Headers::new();
        let mut ctx = Context::new("delayed", &headers, &state, (), &delivery);
        let batch = pull_batch(&mut sub).await;
        handler.handle_batch(batch, &mut ctx).await;

        let mut stream = std::pin::pin!(sub.stream());
        assert!(futures::poll!(stream.next()).is_pending());
        tokio::time::advance(std::time::Duration::from_secs(5)).await;
        tokio::task::yield_now().await;

        let redelivered = stream.next().await.unwrap().unwrap();
        assert_eq!(redelivered.payload(), b"1");
        redelivered.ack().await.unwrap();
    }

    #[tokio::test]
    async fn uniform_outcome_settles_the_whole_batch() {
        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("uniform");
        publish_numbers(&broker, "uniform", &[0, 1]).await;

        let handler = typed_batch(JsonCodec, |_batch: &[u32], _ctx: &mut Context| async {
            HandlerResult::retry()
        });

        let state = ();
        let delivery = Delivery::empty();
        let headers = Headers::new();
        let mut ctx = Context::new("uniform", &headers, &state, (), &delivery);
        let batch = pull_batch(&mut sub).await;
        assert_eq!(batch.len(), 2);
        handler.handle_batch(batch, &mut ctx).await;

        let redelivered = pull_batch(&mut sub).await;
        assert_eq!(redelivered.len(), 2);
        for msg in redelivered {
            msg.ack().await.unwrap();
        }
    }

    fn uniform_outcome(result: BatchResult) -> HandlerResult {
        match result {
            BatchResult::Uniform(outcome) => outcome,
            other => panic!("expected a uniform settlement, got {other:?}"),
        }
    }

    fn per_element_outcomes(result: BatchResult) -> Vec<HandlerResult> {
        match result {
            BatchResult::PerElement(settles) => settles.iter().map(Settle::outcome).collect(),
            other => panic!("expected per-element settlements, got {other:?}"),
        }
    }

    /// Every handler return shape maps onto the settlement the dispatcher applies. The `Result`
    /// forms are the interesting ones: an error drops the batch (it is not replayed), while the
    /// `Ok` payload decides on its own.
    #[test]
    fn handler_returns_map_onto_settlements() {
        assert_eq!(
            uniform_outcome(BatchResult::Uniform(HandlerResult::retry()).into_batch_result()),
            HandlerResult::retry(),
        );
        assert_eq!(
            uniform_outcome(HandlerResult::retry().into_batch_result()),
            HandlerResult::retry(),
        );
        assert_eq!(uniform_outcome(().into_batch_result()), HandlerResult::Ack);
        assert_eq!(
            uniform_outcome(Ok::<(), &str>(()).into_batch_result()),
            HandlerResult::Ack,
        );
        assert_eq!(
            uniform_outcome(Err::<(), &str>("boom").into_batch_result()),
            HandlerResult::drop(),
        );
        assert_eq!(
            uniform_outcome(Ok::<_, &str>(HandlerResult::retry()).into_batch_result()),
            HandlerResult::retry(),
        );
        assert_eq!(
            uniform_outcome(Err::<HandlerResult, &str>("boom").into_batch_result()),
            HandlerResult::drop(),
        );
        assert_eq!(
            per_element_outcomes(vec![Settle::from(HandlerResult::Ack)].into_batch_result()),
            [HandlerResult::Ack],
        );
        assert_eq!(
            per_element_outcomes(vec![HandlerResult::drop()].into_batch_result()),
            [HandlerResult::drop()],
        );
    }

    /// A definition that fills in nothing but the required items, to pin what the trait's own
    /// defaults contribute to a registration.
    struct BareBatch;

    impl BatchDef for BareBatch {
        type Input = Decoded<u32>;
        type Handler = ();
        type Source = Name;

        fn source(&self) -> Self::Source {
            Name::new("bare")
        }

        fn into_handler(self) -> Self::Handler {}
    }

    #[test]
    fn batch_def_defaults_register_without_documentation() {
        let def = BareBatch;
        // The mount site names the registration after the def's own source.
        let source = def.source();
        let name = SubscriptionSource::<ConnectedMemoryBroker>::name(&source).to_owned();
        let meta = batch_metadata(name, &def);

        assert_eq!(meta.name, "bare");
        assert_eq!(meta.input_type, "u32");
        assert!(meta.description.is_none());
        assert!(meta.payload_schema.is_none());
        assert!(meta.headers_schema.is_none());
        assert!(meta.message_name.is_none());
        assert!(meta.message_description.is_none());
        assert_eq!(def.workers(), Workers::sequential());
        assert_eq!(def.failure_policies(), FailurePolicies::default());
    }

    #[test]
    fn typed_batch_debug_reports_the_decode_policy() {
        let handler = typed_batch::<MemoryMessage, u32, _, _>(
            JsonCodec,
            |_batch: &[u32], _ctx: &mut Context| async { HandlerResult::Ack },
        )
        .with_decode(FailurePolicy::Retry);

        let rendered = format!("{handler:?}");
        assert!(rendered.contains("TypedBatch"), "{rendered}");
        assert!(rendered.contains("Retry"), "{rendered}");
    }

    /// A `fail_fast` decode policy tears the service down through the context's shutdown handle,
    /// drops the offending element (it is not requeued into the failure) and still hands the
    /// decodable rest to the handler.
    #[tokio::test]
    async fn fail_fast_decode_tears_down_and_drops_the_element() {
        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("ff-batch");
        publish_payloads(&broker, "ff-batch", &[b"1", b"not json"]).await;

        let seen = Arc::new(Mutex::new(Vec::new()));
        let collected = Arc::clone(&seen);
        let handler = typed_batch(JsonCodec, move |batch: &[u32], _ctx: &mut Context| {
            collected.lock().unwrap().extend_from_slice(batch);
            async { HandlerResult::Ack }
        })
        .with_decode(FailurePolicy::FailFast);

        let token = CancellationToken::new();
        let shutdown = ErrorShutdown::new(token.clone());
        let state = ();
        let delivery = Delivery::empty();
        let headers = Headers::new();
        let mut ctx =
            Context::new("ff-batch", &headers, &state, (), &delivery).with_failfast(&shutdown);
        let batch = pull_batch(&mut sub).await;
        assert_eq!(batch.len(), 2);
        handler.handle_batch(batch, &mut ctx).await;

        assert!(token.is_cancelled(), "a fail-fast decode must tear down");
        let failure = shutdown.peek_failure().expect("a failure must be recorded");
        assert!(failure.contains("ff-batch"), "{failure}");
        assert!(failure.contains("batch decode failed"), "{failure}");
        assert_eq!(*seen.lock().unwrap(), [1]);

        // The undecodable element was dropped, not requeued into the same failure.
        let mut stream = std::pin::pin!(sub.stream());
        assert!(futures::poll!(stream.next()).is_pending());
    }

    /// A delivery whose settlement always fails: the memory broker's own ack cannot fail, so the
    /// ack-failure path needs a delivery that refuses.
    struct UnsettleableMessage(Arc<AtomicUsize>);

    impl IncomingMessage for UnsettleableMessage {
        fn payload(&self) -> &[u8] {
            b"0"
        }

        fn headers(&self) -> &Headers {
            static EMPTY: OnceLock<Headers> = OnceLock::new();
            EMPTY.get_or_init(Headers::new)
        }

        async fn ack(self) -> Result<(), AckError> {
            self.0.fetch_add(1, Ordering::SeqCst);
            Err(AckError::Timeout)
        }

        async fn nack(self, _requeue: bool) -> Result<(), AckError> {
            self.0.fetch_add(1, Ordering::SeqCst);
            Err(AckError::Timeout)
        }
    }

    /// One delivery refusing its ack is a logged diagnostic, not a fatal: the rest of the batch is
    /// still settled.
    #[tokio::test]
    async fn a_refused_ack_does_not_abort_the_batch() {
        let attempts = Arc::new(AtomicUsize::new(0));
        let batch = vec![
            UnsettleableMessage(Arc::clone(&attempts)),
            UnsettleableMessage(Arc::clone(&attempts)),
        ];

        settle_batch(
            batch,
            BatchResult::Uniform(HandlerResult::Ack),
            "refusing",
            &TaskTracker::new(),
        )
        .await;

        assert_eq!(attempts.load(Ordering::SeqCst), 2);
    }

    /// Captures the fields of the events emitted while the guard is alive, so a test can assert on
    /// the diagnostics (needs a tracing subscriber, hence the `logging` feature gate).
    #[cfg(feature = "logging")]
    mod log_capture {
        use std::collections::HashMap;
        use std::fmt::Debug;
        use std::sync::{Arc, Mutex};

        use tracing::Subscriber;
        use tracing::field::{Field, Visit};
        use tracing::subscriber::DefaultGuard;
        use tracing_subscriber::Layer;
        use tracing_subscriber::layer::{Context, SubscriberExt as _};

        pub(super) type Events = Arc<Mutex<Vec<HashMap<String, String>>>>;

        #[derive(Default)]
        struct FieldGrab(HashMap<String, String>);

        impl Visit for FieldGrab {
            fn record_str(&mut self, field: &Field, value: &str) {
                self.0.insert(field.name().to_owned(), value.to_owned());
            }

            fn record_u64(&mut self, field: &Field, value: u64) {
                self.0.insert(field.name().to_owned(), value.to_string());
            }

            fn record_debug(&mut self, field: &Field, value: &dyn Debug) {
                self.0
                    .entry(field.name().to_owned())
                    .or_insert_with(|| format!("{value:?}"));
            }
        }

        struct Capture(Events);

        impl<S: Subscriber> Layer<S> for Capture {
            fn on_event(&self, event: &tracing::Event<'_>, _ctx: Context<'_, S>) {
                let mut grab = FieldGrab::default();
                event.record(&mut grab);
                self.0.lock().unwrap().push(grab.0);
            }
        }

        pub(super) fn start() -> (Events, DefaultGuard) {
            let events: Events = Arc::new(Mutex::new(Vec::new()));
            let guard = tracing::subscriber::set_default(
                tracing_subscriber::registry().with(Capture(Arc::clone(&events))),
            );
            (events, guard)
        }

        pub(super) fn find(events: &Events, message: &str) -> HashMap<String, String> {
            let captured = events.lock().unwrap();
            captured
                .iter()
                .find(|fields| fields.get("message").is_some_and(|m| m == message))
                .cloned()
                .unwrap_or_else(|| panic!("no `{message}` event was emitted"))
        }
    }

    /// The mismatch diagnostic names the subscription and both counts, so the handler bug behind a
    /// short outcome vector is identifiable from the logs alone.
    #[cfg(feature = "logging")]
    #[tokio::test]
    async fn outcome_count_mismatch_is_logged_with_both_counts() {
        let (events, guard) = log_capture::start();

        let attempts = Arc::new(AtomicUsize::new(0));
        let batch = vec![
            UnsettleableMessage(Arc::clone(&attempts)),
            UnsettleableMessage(Arc::clone(&attempts)),
            UnsettleableMessage(Arc::clone(&attempts)),
        ];
        settle_batch(
            batch,
            BatchResult::PerElement(vec![Settle::from(HandlerResult::Ack)]),
            "short-batch",
            &TaskTracker::new(),
        )
        .await;
        drop(guard);

        let mismatch = log_capture::find(
            &events,
            "per-element outcome count does not match the batch; \
             retrying the unmatched remainder",
        );
        assert_eq!(
            mismatch.get("subscription").map(String::as_str),
            Some("short-batch")
        );
        assert_eq!(mismatch.get("expected").map(String::as_str), Some("3"));
        assert_eq!(mismatch.get("returned").map(String::as_str), Some("1"));
    }

    /// The decode and ack-failure diagnostics carry the subscription (plus the element type and the
    /// broker error), so a failure is attributable without a second run.
    #[cfg(feature = "logging")]
    #[tokio::test]
    async fn decode_and_ack_failures_are_logged_with_their_subscription() {
        let broker = MemoryBroker::new();
        let mut sub = broker.subscribe("diag-batch");
        publish_payloads(&broker, "diag-batch", &[b"not json"]).await;

        let (events, guard) = log_capture::start();
        let handler = typed_batch(JsonCodec, |_batch: &[u32], _ctx: &mut Context| async {
            HandlerResult::Ack
        });
        let state = ();
        let delivery = Delivery::empty();
        let headers = Headers::new();
        let mut ctx = Context::new("diag-batch", &headers, &state, (), &delivery);
        let batch = pull_batch(&mut sub).await;
        handler.handle_batch(batch, &mut ctx).await;

        settle_batch(
            vec![UnsettleableMessage(Arc::new(AtomicUsize::new(0)))],
            BatchResult::Uniform(HandlerResult::Ack),
            "diag-batch",
            &TaskTracker::new(),
        )
        .await;
        drop(guard);

        let decode = log_capture::find(&events, "codec decode failed");
        assert_eq!(
            decode.get("subscription").map(String::as_str),
            Some("diag-batch")
        );
        assert_eq!(decode.get("message_type").map(String::as_str), Some("u32"));

        let ack = log_capture::find(&events, "ack / nack failed");
        assert_eq!(
            ack.get("subscription").map(String::as_str),
            Some("diag-batch")
        );
        assert_eq!(
            ack.get("error").map(String::as_str),
            Some(AckError::Timeout.to_string().as_str())
        );
    }
}
