//! Out injection: a handler receives a live publisher as a parameter.
//!
//! `#[subscriber("in")] async fn f(msg: &T, Out(out): Out<P>)` declares that the handler
//! publishes through a `P`. The publisher never lives in the application state: the source is
//! attached where the handler is included (`b.include(f).publisher(source)`), the runtime pairs
//! it against the connected broker at startup, and every dispatch receives the live `P` - fully
//! monomorphized, nothing to check on the hot path.

use std::future::Future;

use serde::de::DeserializeOwned;
use tracing::warn;

use crate::IncomingMessage;
use crate::codec::Codec;

use super::context::Context;
use super::dispatch::Workers;
use super::failure::{FailurePolicies, FailurePolicy};
use super::handler::{Handler, HandlerResult, Settle};
use super::metadata::HandlerMetadata;

/// The marker a handler signature uses to receive an injected publisher:
/// `Out(out): Out<P>` binds `out` to `&P` inside the body.
///
/// The value is paired by the runtime from the source attached at the include site, so it is
/// live by construction; handlers never see a "not connected" state. See the module docs.
///
/// # Examples
///
/// ```
/// # #[cfg(all(feature = "memory", feature = "macros", feature = "json"))]
/// # mod demo {
/// use ruststream::memory::MemoryPublisher;
/// use ruststream::runtime::{HandlerResult, Out};
/// use ruststream::{OutgoingMessage, Publisher, subscriber};
/// # #[derive(serde::Deserialize)]
/// # struct Event { id: u64 }
///
/// #[subscriber("ingress")]
/// async fn forward(event: &Event, Out(out): Out<MemoryPublisher>) -> HandlerResult {
///     let payload = event.id.to_be_bytes();
///     if out
///         .publish(OutgoingMessage::new("out", payload.as_slice()))
///         .await
///         .is_err()
///     {
///         return HandlerResult::retry();
///     }
///     HandlerResult::Ack
/// }
/// # }
/// ```
#[derive(Debug)]
pub struct Out<P>(pub P);

/// A subscriber definition whose handler takes an injected publisher parameter.
///
/// Generated by `#[subscriber(..)]` when the signature carries an [`Out`] parameter; the
/// publisher type is [`Self::Out`], and the include site must attach a source whose live form
/// is exactly that type.
pub trait OutDef: Send + Sync {
    /// The decoded message type the handler consumes.
    type Input;

    /// The broker's typed per-delivery context (see
    /// [`SubscriberDef::Context`](super::SubscriberDef::Context)).
    type Context;

    /// The subscription source this handler binds to.
    type Source;

    /// The live publisher type the handler's [`Out`] parameter names.
    type Out;

    /// Builds the subscription source (fresh each call).
    fn source(&self) -> Self::Source;

    /// The concurrency policy for this subscriber's dispatch loop.
    fn workers(&self) -> Workers {
        Workers::sequential()
    }

    /// The failure policy for a handler panic and a decode failure.
    fn failure_policies(&self) -> FailurePolicies {
        FailurePolicies::default()
    }

    /// An optional human description (from the handler's doc comment), for `AsyncAPI`.
    fn description(&self) -> Option<&str> {
        None
    }

    /// The input type's serialized JSON Schema, when available.
    fn input_schema(&self) -> Option<String> {
        None
    }

    /// The input type's [`Message`](crate::Message) name, when it implements that trait.
    fn message_name(&self) -> Option<&'static str> {
        None
    }

    /// The input type's [`Message`](crate::Message) description, when it implements that trait.
    fn message_description(&self) -> Option<&'static str> {
        None
    }
}

/// Runs an [`OutDef`]'s handler body over an app state of type `S` (the same state-generic
/// shape as [`Handler`](super::Handler); see
/// [`PublishingCall`](super::PublishingCall) for the rationale).
pub trait OutCall<S>: OutDef {
    /// Runs the handler body with the injected live publisher.
    fn call(
        &self,
        input: &Self::Input,
        out: &Self::Out,
        ctx: &mut Context<'_, Self::Context, S>,
    ) -> impl Future<Output = Settle> + Send;
}

/// Builds the registration metadata for an out definition mounted under `name`.
pub(crate) fn out_metadata<D: OutDef>(name: String, def: &D) -> HandlerMetadata {
    HandlerMetadata::typed::<D::Input>(name).with_def_details(
        def.description(),
        def.input_schema(),
        def.message_name(),
        def.message_description(),
    )
}

/// The [`Handler`] built from an [`OutDef`] once its source paired: decode, then run the body
/// with the live publisher.
pub struct OutHandler<D, C, P> {
    pub(crate) def: D,
    pub(crate) codec: C,
    pub(crate) out: P,
    pub(crate) decode: FailurePolicy,
}

impl<D, C, P> std::fmt::Debug for OutHandler<D, C, P> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OutHandler").finish_non_exhaustive()
    }
}

impl<M, D, C, P, S> Handler<M, D::Context, S> for OutHandler<D, C, P>
where
    M: IncomingMessage,
    D: OutCall<S, Out = P>,
    D::Input: DeserializeOwned + Send + Sync,
    D::Context: Send + Sync,
    C: Codec,
    P: Send + Sync,
    S: Send + Sync,
{
    async fn handle(&self, msg: &M, ctx: &mut Context<'_, D::Context, S>) -> Settle {
        let input = match self.codec.decode::<D::Input>(msg.payload()) {
            Ok(value) => value,
            Err(err) => {
                warn!(
                    target: "ruststream::dispatch",
                    subscription = %ctx.name(),
                    message_type = std::any::type_name::<D::Input>(),
                    error = %err,
                    "codec decode failed",
                );
                return match self.decode {
                    FailurePolicy::FailFast => {
                        ctx.fail_fast(&format!("decode failed: {err}"));
                        HandlerResult::drop().into()
                    }
                    other => other
                        .settlement()
                        .unwrap_or_else(HandlerResult::drop)
                        .into(),
                };
            }
        };
        self.def.call(&input, &self.out, ctx).await
    }
}
