//! Publishing subscribers: a handler whose return value is encoded and published.
//!
//! Generated by `#[subscriber("topic", publish)]` and mounted with
//! [`BrokerScope::include_publishing`](super::BrokerScope::include_publishing), which is handed a
//! [`Publication`] (the destination topic + reply codec).

use std::{future::Future, sync::Arc};

use serde::{Serialize, de::DeserializeOwned};
use tracing::warn;

use crate::codec::Codec;
use crate::{IncomingMessage, Publisher};

use super::context::Context;
use super::handler::{Handler, HandlerResult};
use super::publish::{Publication, PublishMiddleware};

/// A subscriber definition that produces a reply to publish.
///
/// The generated type carries the subscribe channel and the reply type; *where* the reply goes
/// (topic) and *how* it is encoded (codec) come from the [`Publication`] passed at wiring time, not
/// from the macro.
pub trait PublishingDef: Send + Sync {
    /// The decoded message type the handler consumes.
    type Input;

    /// The reply type the handler produces, encoded and published.
    type Reply;

    /// The channel (topic) this handler subscribes to.
    fn subscribe_channel(&self) -> &str;

    /// An optional human description (from the handler's doc comment), for `AsyncAPI`.
    fn description(&self) -> Option<&str> {
        None
    }

    /// The input type's serialized JSON Schema, when it implements [`schemars::JsonSchema`] and the
    /// `asyncapi` feature is on. The macro fills this in; the default omits it.
    fn input_schema(&self) -> Option<String> {
        None
    }

    /// Runs the handler body, producing the reply.
    fn call(&self, input: &Self::Input) -> impl Future<Output = Self::Reply> + Send;
}

/// The [`Handler`] built from a [`PublishingDef`]: decode, run, encode the reply, publish, ack.
///
/// `C` decodes the incoming message; the reply is encoded and routed by the [`Publication`].
pub struct PublishingHandler<D, C, P, PC> {
    pub(crate) def: D,
    pub(crate) codec: C,
    pub(crate) publication: Publication<P, PC>,
    pub(crate) pipeline: Arc<[Arc<dyn PublishMiddleware>]>,
}

impl<D, C, P, PC> std::fmt::Debug for PublishingHandler<D, C, P, PC> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PublishingHandler")
            .field("publication", &self.publication)
            .finish_non_exhaustive()
    }
}

impl<M, D, C, P, PC> Handler<M> for PublishingHandler<D, C, P, PC>
where
    M: IncomingMessage,
    D: PublishingDef,
    D::Input: DeserializeOwned + Send + Sync,
    D::Reply: Serialize + Send + Sync,
    C: Codec,
    P: Publisher,
    PC: Codec,
{
    async fn handle(&self, msg: &M, _ctx: &mut Context<'_>) -> HandlerResult {
        let input = match self.codec.decode::<D::Input>(msg.payload()) {
            Ok(value) => value,
            Err(err) => {
                warn!(target: "ruststream::dispatch", error = %err, "codec decode failed");
                return HandlerResult::drop();
            }
        };
        let reply = self.def.call(&input).await;
        if let Err(err) = self.publication.publish(&reply, &self.pipeline).await {
            warn!(target: "ruststream::dispatch", error = %err, "reply publish failed");
        }
        HandlerResult::Ack
    }
}
