//! Publishing subscribers: a handler whose return value is encoded and published.
//!
//! Generated by `#[subscriber("topic", publish("reply-topic", to = "name"))]` and mounted with
//! [`BrokerScope::include_publishing`](super::BrokerScope::include_publishing).

use std::{future::Future, sync::Arc};

use serde::{Serialize, de::DeserializeOwned};
use tracing::warn;

use crate::IncomingMessage;
use crate::codec::Codec;

use super::context::Context;
use super::handler::{Handler, HandlerResult};
use super::publisher_registry::ErasedPublisher;

/// A subscriber definition that produces a reply to publish.
///
/// The generated type carries the subscribe channel, the reply channel, and the name of the
/// publisher (registered with [`RustStream::publisher`](super::RustStream::publisher)) to send the
/// reply through.
pub trait PublishingDef: Send + Sync {
    /// The decoded message type the handler consumes.
    type Input;

    /// The reply type the handler produces, encoded and published.
    type Reply;

    /// The channel (topic) this handler subscribes to.
    fn subscribe_channel(&self) -> &str;

    /// The channel (topic) the reply is published to.
    fn publish_channel(&self) -> &str;

    /// The name of the registered publisher the reply is sent through.
    fn publisher_name(&self) -> &str;

    /// An optional human description (from the handler's doc comment), for `AsyncAPI`.
    fn description(&self) -> Option<&str> {
        None
    }

    /// Runs the handler body, producing the reply.
    fn call(&self, input: &Self::Input) -> impl Future<Output = Self::Reply> + Send;
}

/// The [`Handler`] built from a [`PublishingDef`]: decode, run, encode the reply, publish, ack.
pub struct PublishingHandler<D, C> {
    pub(crate) def: D,
    pub(crate) codec: C,
    pub(crate) publisher: Option<Arc<dyn ErasedPublisher>>,
    pub(crate) topic: String,
}

impl<D, C> std::fmt::Debug for PublishingHandler<D, C> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PublishingHandler")
            .field("topic", &self.topic)
            .field("publisher", &self.publisher.is_some())
            .finish_non_exhaustive()
    }
}

impl<M, D, C> Handler<M> for PublishingHandler<D, C>
where
    M: IncomingMessage,
    D: PublishingDef,
    D::Input: DeserializeOwned + Send + Sync,
    D::Reply: Serialize + Send + Sync,
    C: Codec,
{
    async fn handle(&self, msg: &M, _ctx: &mut Context<'_>) -> HandlerResult {
        let input = match self.codec.decode::<D::Input>(msg.payload()) {
            Ok(value) => value,
            Err(err) => {
                warn!(target: "ruststream::dispatch", error = %err, "codec decode failed");
                return HandlerResult::drop();
            }
        };
        let reply = self.def.call(&input).await;
        let bytes = match self.codec.encode(&reply) {
            Ok(bytes) => bytes,
            Err(err) => {
                warn!(target: "ruststream::dispatch", error = %err, "reply encode failed");
                return HandlerResult::drop();
            }
        };
        if let Some(publisher) = &self.publisher {
            if let Err(err) = publisher.publish_bytes(&self.topic, bytes.as_ref()).await {
                warn!(target: "ruststream::dispatch", error = %err, "reply publish failed");
            }
        } else {
            warn!(
                target: "ruststream::dispatch",
                topic = %self.topic,
                "no publisher registered for reply",
            );
        }
        HandlerResult::Ack
    }
}
