//! Seek injection: a handler receives its own subscription's seeker as a parameter.
//!
//! `#[subscriber(SRC)] async fn f(msg: &T, Seek(seeker): Seek<K>)` declares that the handler
//! repositions the subscription it consumes (skipping forward past a poison region, rewinding
//! after detecting a gap). Nothing is attached at the include site: the runtime opens the
//! subscription at startup and mints the seeker off the live subscriber
//! ([`Seekable::seeker`](crate::Seekable::seeker)) before the first delivery, so every dispatch
//! receives a live `K` - fully monomorphized, nothing to check on the hot path. On a broker
//! without the [`Seekable`](crate::Seekable) capability the mount fails to compile.

use std::future::Future;

use serde::de::DeserializeOwned;
use tracing::warn;

use crate::IncomingMessage;
use crate::codec::Codec;

use super::context::Context;
use super::dispatch::Workers;
use super::failure::{FailurePolicies, FailurePolicy};
use super::handler::{Handler, HandlerResult, Settle};
use super::metadata::HandlerMetadata;

/// The marker a handler signature uses to receive its subscription's seeker:
/// `Seek(seeker): Seek<K>` binds `seeker` to `&K` inside the body.
///
/// The value is minted by the runtime off the subscription's own subscriber right after it
/// opens, so it is live by construction; handlers never see a "not opened" state. See the
/// module docs.
///
/// # Examples
///
/// ```
/// # #[cfg(all(feature = "memory", feature = "macros", feature = "json"))]
/// # mod demo {
/// use ruststream::memory::{MemoryPosition, MemorySeeker, MemorySource};
/// use ruststream::runtime::{HandlerResult, Seek};
/// use ruststream::{Seeker, subscriber};
/// # #[derive(serde::Deserialize)]
/// # struct Job { id: u64, poisoned_until: Option<usize> }
///
/// /// Skips forward past a region the producer marked poisoned.
/// #[subscriber(MemorySource::new("jobs"))]
/// async fn work(job: &Job, Seek(seeker): Seek<MemorySeeker>) -> HandlerResult {
///     if let Some(resume_at) = job.poisoned_until {
///         if seeker.seek(MemoryPosition::sequence(resume_at)).await.is_err() {
///             return HandlerResult::retry();
///         }
///     }
///     HandlerResult::Ack
/// }
/// # }
/// ```
#[derive(Debug)]
pub struct Seek<K>(pub K);

/// A subscriber definition whose handler takes an injected seeker parameter.
///
/// Generated by `#[subscriber(..)]` when the signature carries a [`Seek`] parameter; the seeker
/// type is [`Self::Seeker`], and the subscription source's subscriber must implement
/// [`Seekable`](crate::Seekable) with exactly that seeker.
pub trait SeekDef: Send + Sync {
    /// The decoded message type the handler consumes.
    type Input;

    /// The broker's typed per-delivery context (see
    /// [`SubscriberDef::Context`](super::SubscriberDef::Context)).
    type Context;

    /// The subscription source this handler binds to.
    type Source;

    /// The seeker type the handler's [`Seek`] parameter names.
    type Seeker;

    /// Builds the subscription source (fresh each call).
    fn source(&self) -> Self::Source;

    /// The concurrency policy for this subscriber's dispatch loop.
    fn workers(&self) -> Workers {
        Workers::sequential()
    }

    /// The failure policy for a handler panic and a decode failure.
    fn failure_policies(&self) -> FailurePolicies {
        FailurePolicies::default()
    }

    /// An optional human description (from the handler's doc comment), for `AsyncAPI`.
    fn description(&self) -> Option<&str> {
        None
    }

    /// The input type's serialized JSON Schema, when available.
    fn input_schema(&self) -> Option<String> {
        None
    }

    /// The input type's [`Message`](crate::Message) name, when it implements that trait.
    fn message_name(&self) -> Option<&'static str> {
        None
    }

    /// The input type's [`Message`](crate::Message) description, when it implements that trait.
    fn message_description(&self) -> Option<&'static str> {
        None
    }
}

/// Runs a [`SeekDef`]'s handler body over an app state of type `S` (the same state-generic
/// shape as [`Handler`](super::Handler); see
/// [`PublishingCall`](super::PublishingCall) for the rationale).
pub trait SeekCall<S>: SeekDef {
    /// Runs the handler body with the injected live seeker.
    fn call(
        &self,
        input: &Self::Input,
        seeker: &Self::Seeker,
        ctx: &mut Context<'_, Self::Context, S>,
    ) -> impl Future<Output = Settle> + Send;
}

/// Builds the registration metadata for a seek definition mounted under `name`.
pub(crate) fn seek_metadata<D: SeekDef>(name: String, def: &D) -> HandlerMetadata {
    HandlerMetadata::typed::<D::Input>(name).with_def_details(
        def.description(),
        def.input_schema(),
        def.message_name(),
        def.message_description(),
    )
}

/// The [`Handler`] built from a [`SeekDef`] once its subscription opened: decode, then run the
/// body with the live seeker.
pub struct SeekHandler<D, C, K> {
    pub(crate) def: D,
    pub(crate) codec: C,
    pub(crate) seeker: K,
    pub(crate) decode: FailurePolicy,
}

impl<D, C, K> std::fmt::Debug for SeekHandler<D, C, K> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SeekHandler").finish_non_exhaustive()
    }
}

impl<M, D, C, K, S> Handler<M, D::Context, S> for SeekHandler<D, C, K>
where
    M: IncomingMessage,
    D: SeekCall<S, Seeker = K>,
    D::Input: DeserializeOwned + Send + Sync,
    D::Context: Send + Sync,
    C: Codec,
    K: Send + Sync,
    S: Send + Sync,
{
    async fn handle(&self, msg: &M, ctx: &mut Context<'_, D::Context, S>) -> Settle {
        let input = match self.codec.decode::<D::Input>(msg.payload()) {
            Ok(value) => value,
            Err(err) => {
                warn!(
                    target: "ruststream::dispatch",
                    subscription = %ctx.name(),
                    message_type = std::any::type_name::<D::Input>(),
                    error = %err,
                    "codec decode failed",
                );
                #[cfg(any(feature = "testing", feature = "otel"))]
                ctx.mark_decode_failed();
                return match self.decode {
                    FailurePolicy::FailFast => {
                        ctx.fail_fast(&format!("decode failed: {err}"));
                        HandlerResult::drop().into()
                    }
                    other => other
                        .settlement()
                        .unwrap_or_else(HandlerResult::drop)
                        .into(),
                };
            }
        };
        self.def.call(&input, &self.seeker, ctx).await
    }
}
